# Generated by Django 2.2.5 on 2020-02-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200219_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
